tailwind.config = {
	darkMode: "class",
	theme: {
		extend: {
			"colors": {
				"on-error-container": "#6e0a12",
				"on-primary-fixed-variant": "#006852",
				"on-error": "#fff7f6",
				"secondary-fixed-dim": "#c0dacf",
				"on-secondary-container": "#3f574e",
				"on-secondary-fixed-variant": "#496057",
				"primary": "#036c55",
				"tertiary": "#2f6772",
				"secondary-container": "#cee9dd",
				"secondary-dim": "#40584f",
				"on-surface-variant": "#57615d",
				"primary-fixed-dim": "#90e5c8",
				"outline-variant": "#aab4af",
				"error": "#a83836",
				"primary-container": "#9ef3d6",
				"surface-dim": "#d2ddd6",
				"on-tertiary-fixed-variant": "#2d6570",
				"error-container": "#fa746f",
				"background": "#f6faf6",
				"surface-tint": "#036c55",
				"surface-container": "#e8f0ea",
				"on-tertiary": "#eefbff",
				"surface-container-highest": "#dae5df",
				"on-secondary-fixed": "#2d443c",
				"inverse-primary": "#a9ffe1",
				"surface": "#f6faf6",
				"on-tertiary-fixed": "#034853",
				"on-background": "#2b3530",
				"surface-container-low": "#eff5f0",
				"on-primary-container": "#005d49",
				"surface-variant": "#dae5df",
				"tertiary-container": "#b7eefc",
				"error-dim": "#67040d",
				"on-primary-fixed": "#004938",
				"surface-container-lowest": "#ffffff",
				"secondary-fixed": "#cee9dd",
				"on-primary": "#e4fff3",
				"on-surface": "#2b3530",
				"on-secondary": "#e4fff3",
				"inverse-surface": "#0a0f0d",
				"surface-container-high": "#e1eae5",
				"tertiary-fixed": "#b7eefc",
				"primary-fixed": "#9ef3d6",
				"on-tertiary-container": "#215b66",
				"tertiary-fixed-dim": "#a9e0ed",
				"primary-dim": "#005f4a",
				"tertiary-dim": "#205a65",
				"surface-bright": "#f6faf6",
				"secondary": "#4c645b",
				"inverse-on-surface": "#999e9b",
				"outline": "#727d78"
			},
			"borderRadius": {
				"DEFAULT": "0.125rem",
				"lg": "0.25rem",
				"xl": "0.5rem",
				"full": "0.75rem"
			},
			"fontFamily": {
				"headline": ["Manrope"],
				"body": ["Inter"],
				"label": ["Inter"]
			}
		},
	},
}
